# Use root/example as user/password credentials
services:

  mongo:
    image: mongo:4.4.1-bionic
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - /Users/line/soft/mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: a1chemy
      MONGO_INITDB_ROOT_PASSWORD: 1B2C9046-E3CC-447F-9961-E125759BA44F

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:9000
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: a1chemy
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: 1B2C9046-E3CC-447F-9961-E125759BA44F